### ISSUE TITLE
Currently Returning 0 Results for Today's Standup Query

### ISSUE THREAD

**Issue by sstemann** [ranking-agent/strider#107] opened 2021-03-09 17:11 UTC
https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/pathway.json

**Comment by cbizon** [comment] 2021-03-09 17:16
Not sure if 1) we think we should be able to answer and 2) if the miscapitalization of NCBIGENE is causing problems.

**Comment by patrickkwang** [comment] 2021-03-09 17:51
CAM-KP advertises the ability to provide gene-pathway connections; no other KPs appear to deal with `biolink:Pathway`s. If the CURIE is correctly capitalized as NCBIGENE:1017, Strider maps it to UniProtKB:P24941, according to CAM-KP's preferences, but CAM-KP does not return anything. For the incorrect capitalization, Strider performs no CURIE mapping, and passes the original NCBIGene:1017 to CAM-KP. There are no results in this case, either. In all cases, Strider seems to be behaving properly.

**Comment by patrickkwang** [comment] 2021-03-09 19:37
ARAX gets relationships like these from the source "ARAX/KG2c". There is a service called "RTX KG2" in the SmartAPI registry, which Strider does not use as a KP. But it's /predicates endpoint indicates no gene->pathway relationships...

**Comment by patrickkwang** [comment] 2021-03-09 19:41
It turns out that RTX KG2 _does_ provide results for this query. Should we be using this as a KP? @edeutsch

**Comment by edeutsch** [comment] 2021-03-09 19:54
I think the answer is yes, you can/should be using this KP now. The endpoint has only been up for a week, so maybe be gentle and report any issues you find. I haven't investigated the apparent issue that there's a disconnect between our /predicates and our results? It's possible /predicates is stale? Can you provide a more detailed repro? I don't quite know what to test from the thread above?

**Comment by patrickkwang** [comment] 2021-03-09 20:04
@edeutsch it seems that /predicates should include a number of predicates connecting `biolink:Gene` to `biolink:Pathway`.

**Comment by edeutsch** [comment] 2021-03-09 20:57
ah, I see. I suppose the issue is that genes don't participate in pathways. All genes do is produce gene products and proteins. And those things participate in pathways. So we have plenty of connections between Pathways and GeneProducts and Proteins. And we do have code that if you ask a question about a gene that doesn't make sense but it makes sense in the context of a protein, we'll make that translation for you. But that isn't reflected in /predicates. Another case related to today's architecture discussion. We can extend today's can-o-worms discussion to what should /predicates provide? Should our /predicates include gene participating in pathways and genes interacting with drugs? which is tolerated fallacy? 

Tagging @cbizon to watch the worms escape!

**Comment by cbizon** [comment] 2021-03-09 20:58
I suspect that we might also be able to get gene-pathway from the SRI graph, which has a smartapi registration as well https://monarch-sandbox.cgrb.oregonstate.edu

**Comment by patrickkwang** [comment] 2021-03-09 21:02
Regardless of any inference going on under the hood, my impression is that /predicates should reflect the assertions that the KP is willing and able to make. So if we can ask a question about genes/pathways and get results, it should be in /predicates.

**Comment by edeutsch** [comment] 2021-03-09 22:16
So /predicates should be a full description of everything the KP knows plus all of the "KP reasoning" just merged applied to it? So every KP will have in /predicates "NamedThing related_to NamedThing" even if their underlying data source does not have any such actual assertions? The combinatorics are potentially staggering? and may efficiently obfuscate the real knowledge underneath?

Imagine a KP that is so simple that it has only very detailed relationship between two leaf categories. Their /predicates would be one line. If each node category and edge predicate has 3 parents, then with all the reasoning inference, their /predicates will have 64 entries?

**Comment by cbizon** [comment] 2021-03-10 14:08
Yeah, although I think @patrickkwang is correct, I think @edeutsch makes a good point. 
  I suggest that we move this conversation to : https://github.com/NCATSTranslator/TranslatorArchitecture/discussions/31

I'd amend Patrick's point to be something to "/predicates should reflect the assertions that the KP is willing and able to make, except for assertions that can be trivially derived from other assertions".  But I admit that doesn't roll off the tongue.

**Comment by cbizon** [comment] 2021-03-12 17:26
This is now returning no results

**Comment by patrickkwang** [comment] 2021-03-12 17:31
Was it ever returning results? I thought we had determined that is was _correctly_ returning no results.

**Comment by cbizon** [comment] 2021-03-12 17:39
I think we were somehow returning results... checking the ARS.

The BTE issue https://github.com/biothings/biothings_explorer/issues/176 should allow us to get results.  I'm not sure if its deployed yet, but when it is, we might need to update our internal registry?

**Comment by cbizon** [comment] 2021-03-12 20:28
Turns out that when we were returning results it was from a different (buggy) endpoint, so those were not real.

We should also be able to get Gene/Pathway from the CAM-KP, but it's contingent on this issue: https://github.com/NCATS-Tangerine/cam-pipeline/issues/59

**Comment by cbizon** [comment] 2021-03-17 17:52
WIth the BTE fix, we are now returning results for this query

**Closed by cbizon** 2021-03-17 17:52 UTC
